openapi: 3.0.1
info:
  title: Mojaloop Payment Manager Mgmt Test API
  version: 1.0.0
paths:
  /state:
    get:
      tags:
      - "test"
      summary: "Returns internal state machine context. For testing purposes only!"
      operationId: "getStateMachineContext"
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StateContext"
components:
  schemas:
    StateContext:
      properties:
        dfspCA:
          properties:
            cert:
              type: "string"
            chain:
              type: "string"
            key:
              type: "string"
        dfspClientCert:
          properties:
            id:
              type: "integer"
            csr:
              type: "string"
            cert:
              type: "string"
            privateKey:
              type: "string"
        dfspJWS:
          properties:
            publicKey:
              type: "string"
            privateKey:
              type: "string"
        dfspServerCert:
          properties:
            rootCertificate:
              type: "string"
            intermediateChain:
              type: "string"
            serverCertificate:
              type: "string"
            privateKey:
              type: "string"
        endpointConfig:
          properties:
            ipList:
              type: "array"
              items:
                type: "string"
            callbackHost:
              type: "string"
        hubCa:
          properties:
            intermediateChain:
              type: "string"
            rootCertificate:
              type: "string"
        hubClientCerts:
          type: "array"
          items:
            type: "object"
            properties:
              id:
                type: "string"
              csr:
                type: "string"
              cert:
                type: "string"
        peerJWS:
          type: "array"
          items:
            type: "object"
            properties:
              dfspId:
                type: "string"
              publicKey:
                type: "string"
