openapi: 3.0.0
info:
  title: Mojaloop Payment Manager Management API
  description: API to revoke and recreate keys/certs for Mojaloop Payment Manager
  version: 1.0.0

paths:
  /dfsp/ca/revoke/{dfspId}:
    parameters:
      - name: dfspId
        in: path
        required: true
        description: The ID of the DFSP
        schema:
          type: string
    post:
      tags:
        - DFSP-client-certificates-revoke
      summary: revoke client certificates
      operationId: revokeDfspClientCSR
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StateObject"
      x-swagger-router-controller: DfspCA
  /dfsp/ca/recreate/{dfspId}:
    parameters:
      - name: dfspId
        in: path
        required: true
        description: The ID of the DFSP
        schema:
          type: string
    post:
      tags:
        - DFSP-client-certificates-recreate
      summary: recreate client certificates
      operationId: recreateDfspClientCSR
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StateObject"
      x-swagger-router-controller: DfspCA
  /dfsp/servercerts/revoke/{dfspId}:
    parameters:
      - name: dfspId
        in: path
        required: true
        description: The ID of the DFSP
        schema:
          type: string
    post:
      tags:
        - DFSP-server-certificates-revoke
      summary: revoke server certificates
      operationId: revokeDfspServerCSR
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StateObject"
      x-swagger-router-controller: DfspServerCerts
  /dfsp/servercerts/recreate/{dfspId}:
    parameters:
      - name: dfspId
        in: path
        required: true
        description: The ID of the DFSP
        schema:
          type: string
    post:
      tags:
        - DFSP-server-certificates-recreate
      summary: recreate server certificates
      operationId: recreateDfspServerCSR
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StateObject"
      x-swagger-router-controller: DfspServerCerts
  /dfsp/jwscerts/revoke/{dfspId}:
    parameters:
      - name: dfspId
        in: path
        required: true
        description: The ID of the DFSP
        schema:
          type: string
    post:
      tags:
        - DFSP-jws-certificates-revoke
      summary: revoke JWS certificates
      operationId: revokeDfspJWSCSR
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StateObject"
      x-swagger-router-controller: DfspJWS
  /dfsp/jwscerts/recreate/{dfspId}:
    parameters:
      - name: dfspId
        in: path
        required: true
        description: The ID of the DFSP
        schema:
          type: string
    post:
      tags:
          - DFSP-jws-certificates-recreate
      summary: recreate JWS certificates
      operationId: recreateDfspJWSCSR
      responses:
          "200":
          description: successful operation
          content:
              application/json:
              schema:
                  $ref: "#/components/schemas/StateObject"
      x-swagger-router-controller: DfspJWS

components:
  schemas:
    StateObject:
      title: State
      type: object
      properties:
        status:
          type: string
          description: Indicates the current status of the state.
          enum:
            - pending
            - inProgress
            - completed
            - inError
        stateDescription:
          type: string
          description: Describes the current state.
        errorDescription:
          type: string
          description: Provides details in case of an error.
